apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
data:
  access-token-secret: ZGVtb19hY2Nlc3NfdG9rZW5fc2VjcmV0XzEyMzQ1Njc4OQ==
  refresh-token-secret: ZGVtb19yZWZyZXNoX3Rva2VuX3NlY3JldF8xMjM0NTY3ODk=
