apiVersion: v1
kind: Service
metadata:
  name: user-management-service-service
spec:
  type: NodePort
  selector:
    app: user-management-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32000
